icons = "awesome"

[theme]
name = "slick"

[[block]]
block = "music"
player = "spotify"
buttons = ["play", "next"]

[[block]]
block = "net"
device = "wlp8s0"
ssid = false
ip = false
speed_up = true
graph_up = false
interval = 5

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0


[[block]]
block = "cpu"
interval = 1

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "{average}°"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

